dind-cdb:
  image: louisamoros/dind-cdb
  container_name: dind-cdb
  privileged: true
  expose:
    - "5000"
  environment:
    PORT: "5000"
jenkins-cdb:
  image: louisamoros/jenkins-cdb
  container_name: jenkins-cdb
  ports: 
    - "9000:8080"
  links:
    - dind-cdb
